name: Run tests
run-name: Testing ${{github.event_name}} by ${{github.actor}}

on:
  push:
  pull_request:
    branches:
      - 'develop'

jobs:
  run_lint_format_type_checking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting Check
        run: npm run lint

      - name: Run Formatting Check
        run: npm run prettier

      - name: Run Type Check
        run: npm run tsc

  run_tests:
    needs: [run_lint_format_type_checking]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run Testing
        run: npm run test
